services:
  database:
    image: postgres:18.1-alpine3.22
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER?Set username!}
      - POSTGRES_PASSWORD=${DB_PASSWORD?Set password!}
      - POSTGRES_DB=${DB_DATABASE?Set db name!}
    restart: unless-stopped
    ports:
      - "5433:5432"
    shm_size: 256mb
    volumes:
     - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 30s
      timeout: 15s

  redis:
    image: redis:8.4.0-alpine
    ports:
      - "6379:6379"
    networks:
      - internalNetwork
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - redis_data:/data

networks:
  internalNetwork:
    driver: bridge

volumes:
  db_data:
  redis_data: