from . import Protocol, runtime_checkable


@runtime_checkable
class IUnitOfWork(Protocol):
    def __aenter__(self) -> None: ...
    def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object | None,
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...
