"""muscle group enums

Revision ID: 03289cb594af
Revises: 31ca0308a28d
Create Date: 2026-03-12 18:43:26.490055

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "03289cb594af"
down_revision: str | Sequence[str] | None = "31ca0308a28d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""INSERT INTO muscle_groups (groups, id) VALUES 
                                                ('chest', 1), 
                                                ('back', 2),
                                                ('legs', 3),
                                                ('arms', 4),
                                                ('shoulders', 5)""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE * FROM muscle_groups")
    # ### end Alembic commands ###
