"""exercises table, m2m workout_items table, category and muscle groups tables

Revision ID: 0ff65c0204bd
Revises: 7edf00c41b38
Create Date: 2026-03-12 18:20:30.563856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ff65c0204bd'
down_revision: Union[str, Sequence[str], None] = '7edf00c41b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category', sa.Enum('cardio', 'strength', 'flexibility', name='category'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muscle_groups',
    sa.Column('groups', sa.Enum('chest', 'back', 'legs', 'arms', 'shoulders', name='musclegroups'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('duration_seconds', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('muscle_group_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_items',
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id'),
    sa.UniqueConstraint('workout_id', 'exercise_id', name='workout_items_uc')
    )
    op.create_index(op.f('ix_workout_items_exercise_id'), 'workout_items', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_items_workout_id'), 'workout_items', ['workout_id'], unique=False)
    op.alter_column('workouts', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_workout_items_workout_id'), table_name='workout_items')
    op.drop_index(op.f('ix_workout_items_exercise_id'), table_name='workout_items')
    op.drop_table('workout_items')
    op.drop_table('exercises')
    op.drop_table('muscle_groups')
    op.drop_table('categories')
    # ### end Alembic commands ###
