"""typo

Revision ID: 303b28e38e1e
Revises: adbfca760494
Create Date: 2026-03-05 13:56:43.688008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303b28e38e1e'
down_revision: Union[str, Sequence[str], None] = 'adbfca760494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.drop_column('user', 'list_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('list_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
