"""category enums

Revision ID: 31ca0308a28d
Revises: 0ff65c0204bd
Create Date: 2026-03-12 18:38:05.160693

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "31ca0308a28d"
down_revision: str | Sequence[str] | None = "0ff65c0204bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """INSERT INTO categories (category, id) VALUES ('cardio', 1), ('strength', 2), ('flexibility', 3)"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE * FROM categories")
    # ### end Alembic commands ###
