"""adjusted table

Revision ID: 6edb3af1806d
Revises: 03289cb594af
Create Date: 2026-03-14 16:59:32.668744

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6edb3af1806d"
down_revision: str | Sequence[str] | None = "03289cb594af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises",
        sa.Column("exercise_slug", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "exercises", sa.Column("exercise_id", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "exercises",
        "description",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.drop_column("exercises", "duration_seconds")
    op.drop_column("exercises", "reps")
    op.drop_column("exercises", "distance_km")
    op.add_column(
        "workout_items", sa.Column("reps", sa.Integer(), nullable=True)
    )
    op.add_column(
        "workout_items",
        sa.Column(
            "distance_km", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
    )
    op.add_column(
        "workout_items",
        sa.Column(
            "duration_seconds", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
    )
    op.drop_constraint(
        op.f("workout_items_exercise_id_fkey"),
        "workout_items",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "workout_items", "exercises", ["exercise_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout_items", type_="foreignkey")
    op.create_foreign_key(
        op.f("workout_items_exercise_id_fkey"),
        "workout_items",
        "exercises",
        ["exercise_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("workout_items", "duration_seconds")
    op.drop_column("workout_items", "distance_km")
    op.drop_column("workout_items", "reps")
    op.add_column(
        "exercises",
        sa.Column(
            "distance_km",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column("reps", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "duration_seconds",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "exercises",
        "description",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("exercises", "exercise_id")
    op.drop_column("exercises", "exercise_slug")
    # ### end Alembic commands ###
