"""extented enum

Revision ID: 7edf00c41b38
Revises: 23f1fc715456
Create Date: 2026-03-08 17:56:47.162411

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7edf00c41b38"
down_revision: str | Sequence[str] | None = "23f1fc715456"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ENUM_NAME = "workoutstatuses"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"ALTER TYPE {ENUM_NAME} RENAME VALUE 'SCHEDULED' TO 'scheduled'"
    )
    op.execute(f"ALTER TYPE {ENUM_NAME} RENAME VALUE 'SKIPPED' TO 'skipped'")
    op.execute(f"ALTER TYPE {ENUM_NAME} RENAME VALUE 'FINISHED' TO 'finished'")
    op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE 'in-progress'")
    op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE 'cancelled'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
