"""adjusted table

Revision ID: 8785105b221d
Revises: 6edb3af1806d
Create Date: 2026-03-14 17:05:50.342163

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8785105b221d"
down_revision: str | Sequence[str] | None = "6edb3af1806d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercises", "exercise_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises",
        sa.Column(
            "exercise_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
