"""relathionship

Revision ID: adbfca760494
Revises: b679c62bfb6a
Create Date: 2026-03-05 13:54:12.095008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adbfca760494'
down_revision: Union[str, Sequence[str], None] = 'b679c62bfb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'refresh_tokens', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'user_id')
    # ### end Alembic commands ###
